// <auto-generated />
namespace GAPS.TSC.CONS.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpertRequest_BdLeadName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpertRequest_BdLeadName));
        
        string IMigrationMetadata.Id
        {
            get { return "201507091244422_ExpertRequest_BdLeadName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
