// <auto-generated />
namespace GAPS.TSC.CONS.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddAssignedToTorequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAssignedToTorequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201507071355566_AddAssignedToTorequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
