// <auto-generated />
namespace GAPS.TSC.CONS.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpertRequestsScoping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpertRequestsScoping));
        
        string IMigrationMetadata.Id
        {
            get { return "201507201040366_ExpertRequestsScoping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
