// <auto-generated />
namespace GAPS.TSC.CONS.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pending : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pending));
        
        string IMigrationMetadata.Id
        {
            get { return "201507070833248_pending"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
