// <auto-generated />
namespace GAPS.TSC.Consillium.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpertRequestTeamMemberMap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpertRequestTeamMemberMap));
        
        string IMigrationMetadata.Id
        {
            get { return "201507210540361_ExpertRequestTeamMemberMap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
